<?php

namespace Database\Seeders;

use App\Models\Aed;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
       
        User::updateOrCreate(
            ['email' => 'admin@test.nl'],
            [
                'name' => 'Admin Beheer',
                'password' => Hash::make('password'),
                'is_admin' => 1,
                'email_verified_at' => now(),
            ]
        );

        
        $aedRows = [
            [
                'serienummer_aed' => 'D00000103225',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Cardiac Science - Powerheart G5',
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => 'Benedeneind Noordzijde',
                'huisnummer' => '468',
                'plaats' => 'Benschop',
                'beschrijving' => 'Ingang buurthuis Triangel. Code 2018 en druk daarna op V. (AED Eigendom gemeente Lopik)',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => '28-7-2021: Band verteerd',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2026-12-13',
                'elektroden_vervaldatum' => '2025-08-28',
            ],
            [
                'serienummer_aed' => 'D00000103299',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Cardiac Science - Powerheart G5',
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => 'Kon. Wilhelminastraat',
                'huisnummer' => '27',
                'plaats' => 'Benschop',
                'beschrijving' => 'Sporthal Buitenkast Code 2015 afsluiten met een V. (AED Eigendom gemeente Lopik)',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => '13-6-2022: AED opgeroepen bij een reanimatie. Elektroden vervangen.',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2026-12-13',
                'elektroden_vervaldatum' => '2025-08-28',
            ],
            [
                'serienummer_aed' => 'D00000103341',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Cardiac Science - Powerheart G5',
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => 'Kon. Maximastraat',
                'huisnummer' => '42',
                'plaats' => 'Lopik',
                'beschrijving' => 'Plus Supermarkt Oplaadpunt naast Rolluik, in buitenkast. (AED Eigendom gemeente Lopik)',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => '28-07-2021: Kast beschadigd. (deksel) werkt nog wel.',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2026-12-13',
                'elektroden_vervaldatum' => '2025-08-28',
            ],
            [
                'serienummer_aed' => 'B12K-00403',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Philips - HeartStart FRx',
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => 'Churchilllaan',
                'huisnummer' => '21',
                'plaats' => 'Lopik',
                'beschrijving' => 'Zwembad Lobeke Pantry badmeester (incl kindersleutel). (AED Eigendom gemeente Lopik)',
                'security' => 'Geen code',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2022-05-08',
                'elektroden_vervaldatum' => '2022-06-30',
            ],
            [
                'serienummer_aed' => 'D00000281794',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Cardiac Science - Powerheart G5',
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => 'Churchilllaan',
                'huisnummer' => '21',
                'plaats' => 'Lopik',
                'beschrijving' => 'Zwembad Lobeke Pantry badmeester (incl kindersleutel). (AED Eigendom gemeente Lopik)',
                'security' => 'Geen code',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => '10-7-2023 Dit is een nieuw AED voor het zwembad. Oude Philips is vervangen.',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2028-07-10',
                'elektroden_vervaldatum' => '2027-12-28',
            ],
            [
                'serienummer_aed' => 'D00000103310',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Cardiac Science - Powerheart G5',
                'serienummer' => null,
                'serienummer_kast' => '1831P706',
                'adres' => 'M.A.A. Schakelplein',
                'huisnummer' => '6',
                'plaats' => 'Lopik',
                'beschrijving' => 'Voorzijde pand (Zuidwestingang). (AED Eigendom gemeente Lopik)',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => '08-10-2021: Ingezet bij reanimatie. Pads gedeclareerd/vervangen.',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2026-12-13',
                'elektroden_vervaldatum' => '2025-08-28',
            ],
            [
                'serienummer_aed' => 'D00000103302',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Cardiac Science - Powerheart G5',
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => 'Nicolaas van Catsweg',
                'huisnummer' => '9',
                'plaats' => 'Lopik',
                'beschrijving' => 'VV Cabauw ballenkamer achter keuken Verzorgingsruimte. (AED Eigendom gemeente Lopik)',
                'security' => 'Geen code',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2026-12-13',
                'elektroden_vervaldatum' => '2025-08-28',
            ],
            [
                'serienummer_aed' => 'A15F-14831',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Philips - Heartstart HS1/Home',
                'serienummer' => 'A15F-14831',
                'serienummer_kast' => null,
                'adres' => 'Graaf Floris IV Weg',
                'huisnummer' => '3',
                'plaats' => 'Lopik',
                'beschrijving' => 'Buurthuis Willige Langerak. (AED Eigendom gemeente Lopik)',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => '(Naaste bewoner: Marco 06-4606',
                'opmerkingen' => '28-7-2021: Constateerden dat electroden door lekkage kast nat waren geworden.',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2027-07-15',
                'elektroden_vervaldatum' => '2025-03-06',
            ],
            [
                'serienummer_aed' => 'B25i-01473',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Philips - Heartstart FRX',
                'serienummer' => 'B25i-01473',
                'serienummer_kast' => null,
                'adres' => 'Graaf Floris IV Weg',
                'huisnummer' => '3',
                'plaats' => 'Lopik',
                'beschrijving' => 'Buurthuis Willige Langerak. (AED Eigendom gemeente Lopik)',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => '8-2-2026: KAST EN AED VERVANGEN',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2030-02-01',
                'elektroden_vervaldatum' => '2028-01-04',
            ],
            [
                'serienummer_aed' => 'D00000103274',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Cardiac Science - Powerheart G5',
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => 'Rolafweg Zuid',
                'huisnummer' => '3',
                'plaats' => 'Lopik',
                'beschrijving' => 'Tennis Vereniging Lopik Hal (AED Eigendom gemeente Lopik)',
                'security' => 'Geen code',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2026-12-13',
                'elektroden_vervaldatum' => '2025-08-28',
            ],
            [
                'serienummer_aed' => 'D00000103262',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Cardiac Science - Powerheart G5',
                'serienummer' => null,
                'serienummer_kast' => '1831P719',
                'adres' => 'Uitweg',
                'huisnummer' => '6',
                'plaats' => 'Lopikerkapel',
                'beschrijving' => 'Buurtvereniging Uitweg (AED Eigendom gemeente Lopik)',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2026-12-13',
                'elektroden_vervaldatum' => '2025-08-28',
            ],
            [
                'serienummer_aed' => 'D00000103285',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Cardiac Science - Powerheart G5',
                'serienummer' => null,
                'serienummer_kast' => '1831P713',
                'adres' => 'Kerkstraat',
                'huisnummer' => '7',
                'plaats' => 'Jaarsveld',
                'beschrijving' => 'Hervormd Verenigingsgebouw. Buiten rechts naast de ingang. (AED Eigendom gemeente Lopik)',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2026-12-13',
                'elektroden_vervaldatum' => '2025-08-28',
            ],
            [
                'serienummer_aed' => 'D00000103281',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Cardiac Science - Powerheart G5',
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => 'Dorp',
                'huisnummer' => '32',
                'plaats' => 'Polsbroek',
                'beschrijving' => 'In de steeg naast dorpshuis. De steeg is te bereiken via de parkeerplaats van Dorp 32. (AED Eigendom gemeente Lopik)',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2026-12-13',
                'elektroden_vervaldatum' => '2025-08-28',
            ],
            [
                'serienummer_aed' => 'D00000103272',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Cardiac Science - Powerheart G5',
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => 'Noordzijdseweg',
                'huisnummer' => '97',
                'plaats' => 'Polsbroek',
                'beschrijving' => 'Buiten, zijkant kantine. SPV 81 (AED Eigendom gemeente Lopik)',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => "Theo Sangers Voorzitter SPV81\n06-3433434\n\nC...",
                'opmerkingen' => '28-07-2021: Bij controle bleek dat de stroom niet aangesloten was.',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2026-12-13',
                'elektroden_vervaldatum' => '2025-08-28',
            ],
            [
                'serienummer_aed' => 'D00000103474',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Cardiac Science - Powerheart G5',
                'serienummer' => null,
                'serienummer_kast' => '1831P712',
                'adres' => 'Lopikerweg Oost',
                'huisnummer' => '181',
                'plaats' => 'Lopikerkapel',
                'beschrijving' => 'Buurtvereniging Lopikerkapel. Aan de muur bij de deur van de toiletten. (AED Eigendom gemeente Lopik)',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => '31-07-2021: AED opgeroepen bij inzet maar niet gebruikt.',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2026-12-13',
                'elektroden_vervaldatum' => '2025-08-28',
            ],
            [
                'serienummer_aed' => 'B18E-04755',
                'eigenaar' => 'Rob Verheul',
                'contactpersoon' => 'Rob Verheul',
                'aed_type' => 'Philips - HeartStart FRx',
                'serienummer' => null,
                'serienummer_kast' => '1827P137',
                'adres' => 'Dirck van Delenlaan',
                'huisnummer' => '7',
                'plaats' => 'LOPIK',
                'beschrijving' => 'Aan de muur tussen de twee garages van nummer 7',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2027-11-25',
                'elektroden_vervaldatum' => '2025-05-28',
            ],
            [
                'serienummer_aed' => 'B19E-00745',
                'eigenaar' => 'Fam Vonk',
                'contactpersoon' => 'Rob Verheul /Fam Vonk',
                'aed_type' => 'Philips - HeartStart FRx',
                'serienummer' => null,
                'serienummer_kast' => '1906S017',
                'adres' => 'De Akker',
                'huisnummer' => '18',
                'plaats' => 'Lopik',
                'beschrijving' => 'De Akker 18 aan de schuur. Deze AED is gewonnen via de Rabobank actie',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => "Maaike en Schalk Vonk De Akker 18\n06-44545",
                'opmerkingen' => '21-8-2021 Pads vervangen',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
'batterij_vervaldatum' => '2023-07-01',
                'elektroden_vervaldatum' => '2025-12-12',
            ],
            [
                'serienummer_aed' => 'A19D-04478',
                'eigenaar' => 'Klever BV',
                'contactpersoon' => "Dominik den Butter\ndominik@kleverbv.nl. Indiensttreding",
                'aed_type' => 'Philips - Heartstart HS1/Home',
                'serienummer' => null,
                'serienummer_kast' => 'nvt',
                'adres' => 'Boveneind NZ',
                'huisnummer' => '84',
                'plaats' => 'BENSCHOP',
                'beschrijving' => 'de AED hangt aan oostkant van het woonhuis bij het hek.',
                'security' => 'Geen code',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => "15-11-21 : Contactpersoon bij Klever was \nMat...",
                'opmerkingen' => "8-10-2021: Rob: Electroden vervangen\n6-11-202...",
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2024-08-01',
                'elektroden_vervaldatum' => '2025-10-17',
            ],
            [
                'serienummer_aed' => 'A17B-01325',
                'eigenaar' => 'Kees van Kooten',
                'contactpersoon' => 'Kees van Kooten',
                'aed_type' => 'Philips - Heartstart HS1/Home',
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => 'Cabauwsekade',
                'huisnummer' => '53',
                'plaats' => 'LOPIK',
                'beschrijving' => 'De AED hangt in een niet afgesloten kast in de schuur.',
                'security' => 'Geen code',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => '25-11-2021: AED opgeroepen voor Reanimatie. Check gedaan.',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2022-10-01',
                'elektroden_vervaldatum' => '2025-03-19',
            ],
            [
                'serienummer_aed' => 'A16G-05059',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Philips - Heartstart HS1/Home',
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => 'Cabauwsekade',
                'huisnummer' => '42',
                'plaats' => 'Lopik',
                'beschrijving' => 'Entree. Hal feestzaal. (AED Eigendom gemeente Lopik)',
                'security' => 'Geen code',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2028-07-01',
                'elektroden_vervaldatum' => '2025-03-06',
            ],
            [
                'serienummer_aed' => 'A16G-05059',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Philips FRx',
                'serienummer' => 'B25i-01492',
                'serienummer_kast' => null,
                'adres' => 'Cabauwsekade',
                'huisnummer' => '42',
                'plaats' => 'Lopik',
                'beschrijving' => 'Entree. Hal feestzaal. (AED Eigendom gemeente Lopik)',
                'security' => 'Geen code',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => 'Beheerder Witte Paard',
                'opmerkingen' => '24-1-2026: AED Vervangen',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2030-01-01',
                'elektroden_vervaldatum' => '2028-01-04',
            ],
            [
                'serienummer_aed' => 'D00000250052',
                'eigenaar' => 'Gemeente Lopik',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Cardiac Science - Powerheart G5',
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => 'M.A. Reinaldaweg',
                'huisnummer' => '19',
                'plaats' => 'Lopik',
                'beschrijving' => 'Entree gebouw gemeentewerken. (AED Eigendom gemeente Lopik)',
                'security' => 'Geen code',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2026-08-01',
                'elektroden_vervaldatum' => '2026-11-28',
            ],
            [
                'serienummer_aed' => 'B18E-04758',
                'eigenaar' => 'Lentehof',
                'contactpersoon' => 'Denise Alblas',
                'aed_type' => 'Philips - HeartStart FRx',
                'serienummer' => null,
                'serienummer_kast' => '1845P390',
                'adres' => 'Lentehof (LET OP: Officiele adres is Burgermeester Blankenhof)',
                'huisnummer' => '1',
                'plaats' => 'Lopik',
                'beschrijving' => 'Lentehof. Burgermeester Blankenhof. Buitenkast. Wordt onderhouden door gemeente Lopik',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => '3-12-2021 RV: Was op locatie. Check gedaan. Alles ok.',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2027-11-25',
                'elektroden_vervaldatum' => '2025-07-13',
            ],
            [
                'serienummer_aed' => 'B20L-00483',
                'eigenaar' => 'D.J. Boer',
                'contactpersoon' => 'Harry Timmer',
                'aed_type' => 'Philips - HeartStart FRx',
                'serienummer' => null,
                'serienummer_kast' => '2125S438',
                'adres' => 'Dorp',
                'huisnummer' => '136',
                'plaats' => 'Benschop',
                'beschrijving' => 'Firma: D.J. Boer Aan de muur van de loods aan de zijkant.',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => "Harrie Timmer \n",
                'opmerkingen' => '23-6-2022 Per 22-6-2022 AED in beheer genomen ...',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2025-07-16',
                'elektroden_vervaldatum' => '2025-10-28',
            ],
            [
                'serienummer_aed' => 'B22H-00487',
                'eigenaar' => 'Conny van Apeldoorn',
                'contactpersoon' => 'Conny van Apeldoorn',
                'aed_type' => 'Philips - HeartStart FRx',
                'serienummer' => null,
                'serienummer_kast' => '2209S992',
                'adres' => 'Meester van Dijkelaan',
                'huisnummer' => '21',
                'plaats' => 'Lopik',
                'beschrijving' => 'Zijgevel',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => 'connyvanapeldoorn@gmail.com',
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2026-07-13',
                'elektroden_vervaldatum' => '2024-12-21',
            ],
            [
                'serienummer_aed' => 'B22K-16586',
                'eigenaar' => 'Hans Wisse',
                'contactpersoon' => 'Hans Wisse',
                'aed_type' => 'Philips - HeartStart FRx',
                'serienummer' => null,
                'serienummer_kast' => '1845P393',
                'adres' => 'Dorpstraat',
                'huisnummer' => '32',
                'plaats' => 'Lopik',
                'beschrijving' => 'AED hangt aan de zijmuur van de benedenzaal aan de buitenzijde.',
                'security' => 'Pincode',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2028-06-30',
                'elektroden_vervaldatum' => '2025-03-12',
            ],
            [
                'serienummer_aed' => 'B23A-06808',
                'eigenaar' => 'Ruud Borst',
                'contactpersoon' => 'Ruud Borst',
                'aed_type' => 'Philips - HeartStart FRx',
                'serienummer' => null,
                'serienummer_kast' => '2218S138',
                'adres' => 'Lopikerweg Oost',
                'huisnummer' => '17',
                'plaats' => 'Lopik',
                'beschrijving' => 'Aan de loods van transportbedrijf Ruud Borst',
                'security' => null,
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => 'Ruud Borst',
                'opmerkingen' => '9-12-2023 AED en Kast afgeleverd en opgevoerd in HartslagNu.',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2027-12-04',
                'elektroden_vervaldatum' => '2028-02-20',
            ],
            [
                'serienummer_aed' => null,
                'eigenaar' => 'HOB Aggregaten',
                'contactpersoon' => 'Danny Smiesing',
                'aed_type' => 'CardiAid CT0207RS Halfautomatisch',
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => 'Lopikerweg west',
                'huisnummer' => '34A',
                'plaats' => 'Lopik',
                'beschrijving' => 'De AED hangt in de loods van fam. Kees Benschop',
                'security' => null,
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => "HOB Aggregaten\nContactpersoon Kees Benschop\n",
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2024-10-01',
                'elektroden_vervaldatum' => '2025-01-31',
            ],
            [
                'serienummer_aed' => null,
                'eigenaar' => 'VVE Huis te Vliethof',
                'contactpersoon' => 'Danny Smiesing',
                'aed_type' => 'Philips - HeartStart FRx',
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => 'Lopikerweg Oost',
                'huisnummer' => '164',
                'plaats' => 'Lopikerkapel',
                'beschrijving' => 'Huis te Vliet, aan de rechterzijde van het kasteel / hek',
                'security' => null,
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => 'Danny Smiesing VVE Huis te Vliethof <HuisteVli...',
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2027-08-01',
                'elektroden_vervaldatum' => '2027-01-31',
            ],
            [
                'serienummer_aed' => null,
                'eigenaar' => 'De Bruijn',
                'contactpersoon' => null,
                'aed_type' => null,
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => null,
                'huisnummer' => null,
                'plaats' => null,
                'beschrijving' => null,
                'security' => null,
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => null,
                'elektroden_vervaldatum' => null,
            ],
            [
                'serienummer_aed' => null,
                'eigenaar' => 'Dorp66',
                'contactpersoon' => null,
                'aed_type' => null,
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => null,
                'huisnummer' => null,
                'plaats' => null,
                'beschrijving' => null,
                'security' => null,
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => null,
                'elektroden_vervaldatum' => null,
            ],
            [
                'serienummer_aed' => null,
                'eigenaar' => 'Stichting Hartslag Lopik',
                'contactpersoon' => 'Harry van Schie 06-5343453453',
                'aed_type' => 'Philips - HeartStart FRx',
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => 'Noordzijdseweg 189, 3415 RC Polsbroek, Nederland',
                'huisnummer' => null,
                'plaats' => null,
                'beschrijving' => 'Rustpunt landwinkel De Noordzijde. De AED Hangt buiten onder afdak. Schuin tegenover de boerderij',
                'security' => 'Pin',
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => 'Harry van Schie 06-453454',
                'opmerkingen' => 'AED gedoneerd gekregen van Delta Kabel',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2028-11-07',
                'elektroden_vervaldatum' => '2027-11-20',
            ],
            [
                'serienummer_aed' => null,
                'eigenaar' => 'VVE De Boeg',
                'contactpersoon' => 'Shirley Koole',
                'aed_type' => 'Philips - HeartStart FRx',
                'serienummer' => 'b23a-09528 kast 2414s783',
                'serienummer_kast' => null,
                'adres' => 'Lekdijk oost 16E Lopikerkapel',
                'huisnummer' => null,
                'plaats' => null,
                'beschrijving' => 'Bij ingang beachclub klein scheveningen',
                'security' => null,
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => 'Shirley Koole - 0617078454545797',
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2026-06-18',
                'elektroden_vervaldatum' => '2028-06-17',
            ],
            [
                'serienummer_aed' => null,
                'eigenaar' => 'VVE De Ellenborgh',
                'contactpersoon' => 'Govert Bos',
                'aed_type' => 'Philips - HeartStart FRx',
                'serienummer' => 'b24d-02345',
                'serienummer_kast' => null,
                'adres' => 'Florijn 18',
                'huisnummer' => null,
                'plaats' => 'Benschop',
                'beschrijving' => 'De AED hangt aan de entreedeur van De Ellenborgh',
                'security' => null,
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => 'Govert Bos 0615630645454539 g',
                'opmerkingen' => 'Installatie gedaan op 24-6-2026 door firma Benschop',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2028-06-24',
                'elektroden_vervaldatum' => '2026-08-16',
            ],
            [
                'serienummer_aed' => 'A14G-05419',
                'eigenaar' => 'Lekkerkerker',
                'contactpersoon' => 'Fulco Hokke',
                'aed_type' => 'Philips - Heartstart HS1/Home',
                'serienummer' => 'A14G-05419',
                'serienummer_kast' => null,
                'adres' => 'Handelsweg',
                'huisnummer' => '2',
                'plaats' => 'Lopik',
                'beschrijving' => 'AED hangt buiten rechts aan de muur bij de leveranciersingang. Firma Lekkerkerker',
                'security' => null,
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => 'Fulco Hokke',
                'opmerkingen' => '18-10-2024: Deze AED is op 17-10-2024 buitengeplaatst en opgevoerd in HartslagNu. HartslagNu beheert niet de AED. Lekkerkerker heeft een onderhoudscontract met AED partner. Stichting beheert AED alleen in HartslagNu;',
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2027-01-01',
                'elektroden_vervaldatum' => '2025-03-22',
            ],
            [
                'serienummer_aed' => null,
                'eigenaar' => 'Nobel',
                'contactpersoon' => 'Robert Nobel 06-nummer',
                'aed_type' => null,
                'serienummer' => null,
                'serienummer_kast' => null,
                'adres' => null,
                'huisnummer' => null,
                'plaats' => null,
                'beschrijving' => null,
                'security' => null,
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => null,
                'elektroden_vervaldatum' => null,
            ],
            [
                'serienummer_aed' => 'B25D-10591',
                'eigenaar' => 'HartslagLopik',
                'contactpersoon' => 'Joost van Liempt 06-nummer',
                'aed_type' => 'Philips - HeartStart FRx',
                'serienummer' => 'B25D-10591',
                'serienummer_kast' => null,
                'adres' => 'Lekdijk west 13a',
                'huisnummer' => null,
                'plaats' => 'Lopik',
                'beschrijving' => 'VVE Vijfhoeven',
                'security' => null,
                'pincode' => 'CODE',
                'onderhoudscode' => 'CODE',
                'lokaal_contactpersoon' => null,
                'opmerkingen' => null,
                'cooperation_agreement_path' => null,
                'status' => 'actief',
                'batterij_vervaldatum' => '2029-11-01',
                'elektroden_vervaldatum' => '2028-02-20',
            ],
        ];

        foreach ($aedRows as $row) {
            $uniqueKey = $row['serienummer_aed'] ?? $row['serienummer'];


            if (!$uniqueKey && empty($row['eigenaar']) && empty($row['adres']) && empty($row['beschrijving'])) {
                continue;
            }

            // Deze seeder bevat ook rijen waar verplichte velden null kunnen zijn.
            // Omdat de databasekolommen NOT NULL zijn: sla die rijen over.
            foreach (['aed_type', 'huisnummer'] as $required) {
                if (!isset($row[$required]) || $row[$required] === null || $row[$required] === '') {
                    continue 2;
                }
            }


            Aed::updateOrCreate(
                [
                    'serienummer_aed' => $uniqueKey,
                ],
                $row
            );
        }
    }
}